version: '3.7'

services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data -cors *"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    user: root
    working_dir: /home/dynamodblocal
    ports:
      - "8000:8000"
    volumes:
      - "dynamodb-data:/home/dynamodblocal/data"

  dynamodb-admin:
    container_name: dynamodb-admin
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-local:8000"
      AWS_REGION: "us-west-2"
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    depends_on:
      - dynamodb-local

volumes:
  dynamodb-data:
