version: '3.8'

services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data -cors *"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    user: root
    ports:
      - "8000:8000"
    volumes:
      - "dynamodb-data:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

volumes:
  dynamodb-data: